# 3.1 인공신경망의 구성요소

- 작성자: [김찬란](https://github.com/seriousran)

In [1]:
# 코드 3-1 벡터 예제
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x)

(12,)
1
int64
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [2]:
# 코드 3-2 행렬 변환 예제

A = x.reshape((3,4))
print(A.shape)
print(A.ndim)
print(A.dtype)
print(A)

(3, 4)
2
int64
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
# 코드 3-3 포트란식 행렬 변환 예제

A = x.reshape((3,4), order='F') # Fortran-like index ordering
print(A.shape)
print(A.ndim)
print(A.dtype)
print(A)

(3, 4)
2
int64
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [4]:
# 코드 3-4 다차원 행렬 변환 예제

A = x.reshape((3, 2, 2))
print(A.shape)
print(A.ndim)
print(A.dtype)
print(A)

(3, 2, 2)
3
int64
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [5]:
# 코드 3-5 케라스 함수형 API 예제

from keras.layers import Input, Dense
from keras.models import Model

inputs = Input(shape=(512,))

x1 = Dense(64, activation='relu')(inputs)
x2 = Dense(64, activation='relu')(x1)
outputs = Dense(10, activation='softmax')(x2)

model = Model(inputs=inputs, outputs=outputs)
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(data, labels) 

# 아직 준비된 데이터가 없기 때문에 실행할 경우 에러가 나는 것이 맞습니다.

Using TensorFlow backend.


NameError: ignored

In [0]:
# 코드 3-6 Input 레이어의 예

inputs = Input(shape=(512,))

In [7]:
# 코드 3-7 Dense 레이어의 예-1

Dense(64, input_shape=(512,))

In [8]:
# 코드 3-8 Dense 레이어의 예-2

Dense(10, activation='relu')(x)

# 아직 준비된 데이터가 없기 때문에 실행할 경우 에러가 나는 것이 맞습니다.

ValueError: ignored

In [0]:
# 코드 3-9 간단한 모델의 예

inputs = Input(shape=(3,))
fc1 = Dense(4, activation='relu')(inputs)
outputs = Dense(1, activation='softmax')(fc1)
model = Model(inputs, outputs)